---
title: "Data Preparation: ascertainment of pregnancy outcomes"
author: "Laura Symul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
---



```{r data_prep_po setup, include = FALSE, eval = TRUE, cache = FALSE}
source("Scripts/00_setup.R")
```

```{r data_prep_po knitr options}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


## Pregnancy outcomes

```{r data_prep_po load users and cycles for the pregnancy outcomes}

users = read_feather(path = paste0(IO$output_data, "users.feather"))
cycles = read_feather( path = paste0(IO$output_data, "cycles.feather"))
pregnancies = read_feather( path = paste0(IO$output_data, "pregnancies.feather"))


```


### For each pregnancy

```{r data_prep_po preg outcome}

cycles$preg_outcome_based_on_duration = factor(cycles$preg_test_class, 
                             levels = c(dict$pregnancy_timeline$abbreviation,
                                        unique(cycles$preg_test_class)))

j = which(cycles$preg_test_class == "pregnant")

cycles$preg_outcome_based_on_duration[j] = cut(cycles$cycle_length[j], 
                             breaks = c(0,dict$pregnancy_timeline$duration_in_days), 
                             labels = as.character(dict$pregnancy_timeline$abbreviation))



cycles$cycle_length_next_cycle = cycles$cycle_length[match(paste0(cycles$user_id, "_",cycles$cycle_nb+1),cycles$cycle_id)]

cycles$preg_outcome_cat = as.character(cycles$preg_outcome_based_on_duration)
cycles$preg_outcome_cat[cycles$preg_outcome_based_on_duration == "TB noBF"] = "TB noBF (II)"
cycles$preg_outcome_cat[cycles$preg_outcome_based_on_duration == "BF"] = "TB BF (II)"
cycles$preg_outcome_cat[which((cycles$preg_outcome_cat == "TB") & (cycles$cycle_length_next_cycle <= 7*9))] = "TB noBF (I)"
cycles$preg_outcome_cat[which((cycles$preg_outcome_cat == "TB") & (cycles$cycle_length_next_cycle > 7*9))] = "TB BF (I)"
cycles$preg_outcome_cat[which((cycles$preg_outcome_cat == "TB") & (is.na(cycles$cycle_length_next_cycle)))] = "TB (III)"
cycles$preg_outcome = dict$pregnancy_outcomes$categories[match(cycles$preg_outcome_cat, dict$pregnancy_outcomes$abbreviation)]
cycles$preg_outcome_cat = factor(cycles$preg_outcome_cat, levels = unique(dict$pregnancy_outcomes$abbreviation))
cycles$preg_outcome = factor(cycles$preg_outcome, levels = unique(dict$pregnancy_outcomes$categories))

counts = table(cycles$preg_outcome_cat[j])

table(cycles$preg_outcome_cat[j])/sum(cycles$preg_outcome_cat %in% c("EPL","LPL","ExPTB","PTB","TB noBF (I)","TB noBF (II)","TB (III)","TB BF (I)","TB BF (II)"))


m = match(pregnancies$pregnancy_id, cycles$cycle_id)
pregnancies$preg_outcome_based_on_duration = cycles$preg_outcome_based_on_duration[m]
pregnancies$preg_outcome_cat = cycles$preg_outcome_cat[m]
pregnancies$preg_outcome = cycles$preg_outcome[m]


write_feather(cycles, path = paste0(IO$output_data, "cycles.feather"))
file.copy(from = paste0(IO$output_data, "cycles.feather"), to = paste0(IO$tmp_data, "cycles_with_preg_outcome.feather"), overwrite = TRUE)


write_feather(pregnancies, path = paste0(IO$output_data, "pregnancies.feather"))
file.copy(from = paste0(IO$output_data, "pregnancies.feather"), to = paste0(IO$tmp_data, "pregnancies_with_preg_outcome.feather"), overwrite = TRUE)


```


### Aggregates per users


```{r data_prep_po preg outcome per users}

users_preg_outcome =  ddply(cycles, 
                            .(user_id), 
                            .fun = summarize,
                            n_preg = sum(preg_test_class == "pregnant", na.rm = TRUE),
                            n_PL = sum(preg_outcome %in% c("EPL","LPL"), na.rm = TRUE),
                            n_LB = sum(preg_outcome %in% c("ExPTB","PTB","TB noBF","BF"), na.rm = TRUE)
                            
)

table(users_preg_outcome$n_LB, users_preg_outcome$n_PL)
table(users_preg_outcome$n_LB)
table(users_preg_outcome$n_PL)


j = which((users_preg_outcome$n_LB + users_preg_outcome$n_PL)>0)
table(users_preg_outcome$n_LB[j], users_preg_outcome$n_PL[j])
table(users_preg_outcome$n_LB[j])
round(table(users_preg_outcome$n_LB[j])/sum(table(users_preg_outcome$n_LB[j])) * 100, 2)

table(users_preg_outcome$n_PL[j])
round(table(users_preg_outcome$n_PL[j])/sum(table(users_preg_outcome$n_PL[j])) * 100, 2)


dim(users)
dim(users_preg_outcome)

colnames = colnames(users_preg_outcome[,2:ncol(users_preg_outcome)])
m = match(users$user_id, users_preg_outcome$user_id)
for(colname in colnames){
  eval(parse(text = paste0("users$",colname," = users_preg_outcome$",colname,"[m]")))
}

write_feather(users, path = paste0(IO$output_data, "users.feather"))
file.copy(from = paste0(IO$output_data, "users.feather"), to = paste0(IO$tmp_data, "users_with_preg_outcome.feather"), overwrite = TRUE)

```

