---
title: "Pregnancy losses"
author: "Laura Symul"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  bookdown::html_document2: 
    theme: flatly
    highlight: haddock
    toc: yes
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
---



```{r PL_descr setup, include = FALSE, eval = TRUE, cache = FALSE}
source("Scripts/00_setup.R")
```

```{r PL_descr knitr options}
knitr::opts_chunk$set(echo = TRUE, cache = TRUE)
```


# Pregnancy losses

## Histogram of cycle length

- for cycles with positive pregnancy tests, with only negative pregnancy tests and with no pregnancy tests.

- thresholds for EPL (Early Pregnancy loss), LPL_P (Late Pregnancy loss or premature birth), LB (live birth) and BF (breast feeding)



```{r PL_descr load data}

users = read_feather(path = paste0(IO$output_data, "users.feather"))
cycles = read_feather(path = paste0(IO$output_data, "cycles.feather"))
#load(paste0(IO$output_data, "days.Rdata"), verbose = TRUE)

```

```{r PL_descr histograms }

g = ggplot(cycles, aes(x = cycle_length, fill = preg_test_class)) + 
  geom_histogram(aes(y = ..density..), binwidth = 1, position = "identity")+
  xlim(c(0,750))+
  facet_grid(preg_test_class ~ .)
g



g = ggplot(cycles[cycles$preg_test_class != "pregnant",], aes(x = cycle_length, fill = preg_test_class)) + 
  geom_histogram(aes(y = ..density..), binwidth = 1, position = "identity", alpha = 0.5)+
  xlim(c(0,150))
  #facet_grid(preg_test_class ~ .)
g




g_hist_lt = ggplot(cycles, aes(x = cycle_length, fill = preg_test_class)) + 
  geom_vline(xintercept = dict$pregnancy_timeline$duration_in_days, col = "gray", linetype = 2)+
  geom_histogram(aes(y = ..density..), binwidth = 7, position = "identity", alpha = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_m*28, minor_breaks = viz$xaxis_s*7,  labels = viz$xaxis_m*4, limits = c(0,20*28))+
  ylab("% of cycles")+ xlab("cycle or pregnancy duration (in weeks)")+
  scale_fill_discrete(name = "Cycle label")+ theme(legend.position = "bottom")
g_hist_lt

g_hist_st = ggplot(cycles, aes(x = cycle_length, fill = preg_test_class)) +   
  geom_vline(xintercept = dict$pregnancy_timeline$duration_in_days, col = "gray", linetype = 2)+
  geom_histogram(aes(y = ..density..), binwidth = 1, position = "identity", alpha = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_m*28, minor_breaks = viz$xaxis_s*7,  labels = viz$xaxis_m*4, limits = c(0,150))+
  ylab("% of cycles")+ xlab("cycle or pregnancy duration (in weeks)")+
  guides(fill = FALSE)
  #facet_grid(preg_test_class ~ .)
g_hist_st


g_inset = ggplotGrob(g_hist_st +
                  theme(plot.background = element_rect(colour = "gray40")))


g_hist_lt + annotation_custom(
    grob = g_inset,
    xmin = 24*7,
    xmax = Inf,
    ymin = 0.03,
    ymax = Inf
  )


```



```{r PL_descr histograms with reprod objectives , eval = FALSE}

cycles$reprod_obj = users$reprod_obj[match(cycles$user_id, users$user_id)]

g_hist_lt = ggplot(cycles[!is.na(cycles$preg_test_class),], aes(x = cycle_length, fill = reprod_obj )) + 
  geom_vline(xintercept = dict$pregnancy_timeline$duration_in_days, col = "gray", linetype = 2)+
  geom_histogram(aes(y = ..density..), binwidth = 7, position = "identity", alpha = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_m*28, minor_breaks = viz$xaxis_s*7,  labels = viz$xaxis_m*4, limits = c(0,20*28))+
  ylab("% of cycles")+ xlab("cycle or pregnancy duration (in weeks)")+
  scale_fill_discrete(name = "Cycle label")+ theme(legend.position = "bottom")+
  facet_grid(preg_test_class~.)
g_hist_lt

g_hist_st = ggplot(cycles[!is.na(cycles$preg_test_class),], aes(x = cycle_length, fill = reprod_obj)) +   
  geom_vline(xintercept = dict$pregnancy_timeline$duration_in_days, col = "gray", linetype = 2)+
  geom_histogram(aes(y = ..density..), binwidth = 1, position = "identity", alpha = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_m*28, minor_breaks = viz$xaxis_s*7,  labels = viz$xaxis_m*4, limits = c(0,150))+
  ylab("% of cycles")+ xlab("cycle or pregnancy duration (in weeks)")+
  facet_grid(preg_test_class ~ .)
g_hist_st


g_inset = ggplotGrob(g_hist_st +
                  theme(plot.background = element_rect(colour = "gray40")))


g_hist_lt + annotation_custom(
    grob = g_inset,
    xmin = 24*7,
    xmax = Inf,
    ymin = 0.03,
    ymax = Inf
  )


```



```{r PL_descr preg outcome}

cycles$preg_outcome_based_on_duration = factor(cycles$preg_test_class, 
                             levels = c(dict$pregnancy_timeline$abbreviation,
                                        unique(cycles$preg_test_class)))

j = which(cycles$preg_test_class == "pregnant")

cycles$preg_outcome_based_on_duration[j] = cut(cycles$cycle_length[j], 
                             breaks = c(0,dict$pregnancy_timeline$duration_in_days), 
                             labels = as.character(dict$pregnancy_timeline$abbreviation))



cycles$cycle_length_next_cycle = cycles$cycle_length[match(paste0(cycles$user_id, "_",cycles$cycle_nb+1),cycles$cycle_id)]

cycles$preg_outcome_cat = as.character(cycles$preg_outcome_based_on_duration)
cycles$preg_outcome_cat[cycles$preg_outcome_based_on_duration == "TB noBF"] = "TB noBF (II)"
cycles$preg_outcome_cat[cycles$preg_outcome_based_on_duration == "BF"] = "TB BF (II)"
cycles$preg_outcome_cat[which((cycles$preg_outcome_cat == "TB") & (cycles$cycle_length_next_cycle <= 7*9))] = "TB noBF (I)"
cycles$preg_outcome_cat[which((cycles$preg_outcome_cat == "TB") & (cycles$cycle_length_next_cycle > 7*9))] = "TB BF (I)"
cycles$preg_outcome_cat[which((cycles$preg_outcome_cat == "TB") & (is.na(cycles$cycle_length_next_cycle)))] = "TB (III)"
cycles$preg_outcome = dict$pregnancy_outcomes$categories[match(cycles$preg_outcome_cat, dict$pregnancy_outcomes$abbreviation)]
cycles$preg_outcome_cat = factor(cycles$preg_outcome_cat, levels = unique(dict$pregnancy_outcomes$abbreviation))
cycles$preg_outcome = factor(cycles$preg_outcome, levels = unique(dict$pregnancy_outcomes$categories))

counts = table(cycles$preg_outcome_cat[j])

table(cycles$preg_outcome_cat[j])/sum(cycles$preg_outcome_cat %in% c("EPL","LPL","ExPTB","PTB","TB noBF (I)","TB noBF (II)","TB (III)","TB BF (I)","TB BF (II)"))


j = which(cycles$preg_test_class == "pregnant")

ggplot(cycles[j,], aes(x = preg_outcome, fill = preg_outcome_cat)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  xlab("Pregnancy outcome")+ ylab("% cycles")+
  scale_fill_manual(values = dict$pregnancy_outcomes$colors)+
  scale_y_continuous(labels=percent)+
  guides(fill = FALSE)

write_feather(cycles, path = paste0(IO$output_data, "cycles.feather"))
file.copy(from = paste0(IO$output_data, "cycles.feather"), to = paste0(IO$tmp_data, "cycles_with_preg_outcome.feather"), overwrite = TRUE)

```




```{r PL_descr preg outcome per users}

users_preg_outcome =  ddply(cycles, 
                            .(user_id), 
                            .fun = summarize,
                            n_preg = sum(preg_test_class == "pregnant", na.rm = TRUE),
                            n_PL = sum(preg_outcome %in% c("EPL","LPL"), na.rm = TRUE),
                            n_LB = sum(preg_outcome %in% c("ExPTB","PTB","TB noBF","BF"), na.rm = TRUE)
                            
)

table(users_preg_outcome$n_LB, users_preg_outcome$n_PL)
table(users_preg_outcome$n_LB)
table(users_preg_outcome$n_PL)


j = which((users_preg_outcome$n_LB + users_preg_outcome$n_PL)>0)
table(users_preg_outcome$n_LB[j], users_preg_outcome$n_PL[j])
table(users_preg_outcome$n_LB[j])
round(table(users_preg_outcome$n_LB[j])/sum(table(users_preg_outcome$n_LB[j])) * 100, 2)

table(users_preg_outcome$n_PL[j])
round(table(users_preg_outcome$n_PL[j])/sum(table(users_preg_outcome$n_PL[j])) * 100, 2)


dim(users)
dim(users_preg_outcome)

colnames = colnames(users_preg_outcome[,2:ncol(users_preg_outcome)])
m = match(users$user_id, users_preg_outcome$user_id)
for(colname in colnames){
  eval(parse(text = paste0("users$",colname," = users_preg_outcome$",colname,"[m]")))
}

write_feather(users, path = paste0(IO$output_data, "users.feather"))
file.copy(from = paste0(IO$output_data, "users.feather"), to = paste0(IO$tmp_data, "users_with_preg_outcome.feather"), overwrite = TRUE)

```


```{r PL_descr type0 and type1 users}

type0_users = (users$first_cycle_preg == 0) | (users$n_cycles_after_last_preg == 0) | is.na(users$first_cycle_preg)
type1_users = !type0_users

users$is_type_1_user = type1_users


write_feather(users, path = paste0(IO$output_data, "users.feather"))
file.copy(from = paste0(IO$output_data, "users.feather"), to = paste0(IO$tmp_data, "users_with_type.feather"), overwrite = TRUE)

```






```{r PL_descr voluntary vs spontaneous PL}


load(paste0(IO$output_data,"days.Rdata"), verbose = TRUE)

dim(days)
lu(days$user_id)


# sexual intercourse before first positive pregnancy test


```

