---
title: "Pregnancy loss - FIGURES"
author: "Laura Symul"
date: "4/18/2019"
output: html_document
---

```{r figures setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("Scripts/00_setup.R")
```

# Table 1

```{r figures table 1}

load(paste0(IO$output_data, "users.Rdata"), verbose = TRUE)
load(paste0(IO$output_data, "cycles.Rdata"), verbose = TRUE)


table_1 = data.frame(Attribute = "Number of users", Value = nrow(users))
table_1 = rbind(table_1, data.frame(Attribute = "Total number of cycles", Value = sum(users$n_cycles)) )
table_1 = rbind(table_1, data.frame(Attribute = "Number of cycles per users (mean ± sd) ", 
                                    Value = paste0(round(mean(users$n_cycles),2)," ± ",
                                                   round(sd(users$n_cycles),2)) ))

table_1 = rbind(table_1, data.frame(Attribute = "Tracking duration per user [in years] (mean ± sd)", 
                                    Value = paste0(round(mean(users$app_usage_duration_in_years, na.rm = TRUE),2)," ± ",
                                                   round(sd(users$app_usage_duration_in_years, na.rm = TRUE),2)) ))

table_1 = rbind(table_1, data.frame(Attribute = "Total number of positive preg. tests", Value = sum(users$n_pos_cycles)) )

table_1

write.csv(table_1, file = paste0(IO$tables,"dataset_info.csv"))


```



# Figure 1

```{r figures users examples}

load(paste0(IO$tmp_data,"days_selected_users.Rdata"), verbose = TRUE)

user_ids = unique(days$user_id)

for(user in user_ids){
  cat("\n",user, "\n")
  d = days[which((days$user_id == user) & (days$cycle_nb >= 2)),]
  plot.tracking.history(d = d, show_tests = TRUE, average_temp = FALSE)
  
  pdf(file = paste0(IO$panels,"example_",user,".pdf"), width = 9, height = 3.5)
  plot.tracking.history(d = d, show_tests = TRUE, average_temp = FALSE)
  dev.off()
  
}

```



# Figure 2

```{r figures cycle length histogram}

load(file = paste0(IO$output_data, "cycles.Rdata"), verbose = TRUE)


lt_weeks = 84

g_hist_lt = ggplot(cycles[cycles$preg_test_class == "pregnant",], 
                   aes(x = cycle_length, fill = preg_test_class)) + 
  geom_vline(xintercept = dict$pregnancy_timeline$duration_in_days[dict$pregnancy_timeline$duration_in_weeks <= lt_weeks], 
             col = "gray", linetype = 2)+
  geom_histogram(aes(y = ..density..), binwidth = 7, position = "identity", alpha = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_m*28, minor_breaks = viz$xaxis_s*7,  
                     labels = viz$xaxis_m*4, limits = c(0,lt_weeks*7), expand = c(0,0))+
  ylab("% of cycles")+ xlab("cycle or pregnancy duration (in weeks)")+ # ylab("% of cycles")
  scale_fill_manual(name = "Cycle label", values = c("royalblue1"))+ 
  theme(legend.position = "bottom")+
  guides(fill = FALSE)
#g_hist_lt


st_weeks = 22

g_hist_st = ggplot(cycles, aes(x = cycle_length, fill = preg_test_class, group = preg_test_class)) +   
  geom_vline(xintercept = dict$pregnancy_timeline$duration_in_days[dict$pregnancy_timeline$duration_in_weeks <= st_weeks], 
             col = "gray", linetype = 2)+
  geom_histogram(aes(y = ..density.. ), binwidth = 1, position = "identity", alpha = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_m*28, minor_breaks = viz$xaxis_s*7,  
                     labels = viz$xaxis_m*4, limits = c(0,st_weeks*7), expand = c(0,0))+
  ylab("density")+ xlab("cycle or pregnancy duration (in weeks)")+ # ylab("% of cycles")
  scale_fill_manual(name = "Cycle label",values = c("tomato","lightgoldenrod4","royalblue1"))+ 
  theme(legend.position = "right")
#facet_grid(preg_test_class ~ .)
#g_hist_st


g_inset = ggplotGrob(g_hist_st +
                  theme(plot.background = element_rect(colour = "gray40")))


g = g_hist_lt + annotation_custom(
    grob = g_inset,
    xmin = 18*7,
    xmax = Inf,
    ymin = 0.005,
    ymax = Inf
  )

g

ggsave(filename = paste0(IO$panels, "cycle or pregnancy duration.pdf"), g, width = 7, height = 5)

```



```{r figures pregnancy outcomes}

load(file = paste0(IO$output_data, "cycles.Rdata"), verbose = TRUE)

j = which(cycles$preg_test_class == "pregnant")

g = ggplot(cycles[j,], aes(x = preg_outcome, fill = preg_outcome)) + 
  geom_bar(aes(y = (..count..)/sum(..count..)))+
  xlab("Pregnancy outcome")+ ylab("% cycles")+
  scale_fill_manual(values = dict$pregnancy_timeline$colors)+
  scale_y_continuous(labels=percent)+
  guides(fill = FALSE)

g


ggsave(filename = paste0(IO$panels, "pregnancy outcomes.pdf"), g, width = 5, height = 5)

table(cycles$preg_outcome[j])
x = round(table(cycles$preg_outcome[j])/sum(table(cycles$preg_outcome[j])) * 100 ,2)
x

```

```{r figures outcomes table}


table(users$n_LB, users$n_PL)
table(users$n_LB)
table(users$n_PL)


j = which((users$n_LB + users$n_PL)>0)
#table(users$n_LB[j], users$n_PL[j])
table(users$n_LB[j])
round(table(users$n_LB[j])/sum(table(users$n_LB[j])) * 100, 2)

table(users$n_PL[j])
round(table(users$n_PL[j])/sum(table(users$n_PL[j])) * 100, 2)


```





# Figure 3


```{r figures live birth and PL rate}


users$LB_rate = users$n_LB/users$app_usage_duration_in_years

hist(users$LB_rate)

users$PL_rate = users$n_PL/users$app_usage_duration_in_years
hist(users$PL_rate)


g_live_births_rate = ggplot(users[j,], aes(x = LB_rate))+
  geom_histogram(aes(y = ..count../sum(..count..)),binwidth = 1/20, fill = "seagreen3")+
  ylab("% of users")+xlab("# of live births / app usage duration in years")+
  scale_y_continuous(breaks = seq(0,1,1/10), labels = percent)+
  scale_x_continuous(limits = c(-0.15,2.15))
g_live_births_rate

g_PL_rate = ggplot(users[j,], aes(x = PL_rate))+
  geom_histogram(aes(y = ..count../sum(..count..)),binwidth = 1/20, fill = "orange")+
  ylab("% of users")+xlab("# of pregnancy loss / app usage duration in years")+
  scale_y_continuous(breaks = seq(0,1,1/10), labels = percent)+
  scale_x_continuous(limits = c(-0.15,2.15))
g_PL_rate


g = grid.arrange(g_live_births_rate, g_PL_rate)



ggsave(filename = paste0(IO$panels, "live birth and PL rate.pdf"), g, width = 5, height = 5)


```



# Figure 4



```{r figures pregnancy loss predictors}

load(file = paste0(IO$output_data,"users.Rdata"), verbose = TRUE)

users$any_PL = ifelse(users$n_PL>0, "Yes", ifelse(users$n_LB>0,"No",NA))


u = users[which(!is.na(users$first_preg_outcome_simple)),]
u$is_first_preg_a_PL = (u$first_preg_outcome_simple == "PL")


glm_cl = glm(
  is_first_preg_a_PL ~ 
    sd_cycle_length_4+
    median_cycle_length_4+
    time_to_first_pos_test,
  data = u,
  family = "binomial")

summary(glm_cl)


u$is_first_preg_a_PL = ifelse(u$is_first_preg_a_PL,"Yes","No")


g = ggplot(u, aes(x = median_cycle_length_4, fill = is_first_preg_a_PL))+
  geom_histogram(aes(y = ..density..), col = NA, alpha = 0.3, position = "identity", binwidth = 1)+
  scale_x_continuous(breaks = viz$xaxis_j, limits = c(14,70))+
  scale_fill_manual(name = "Does 1st pregnancy end up in a preg. loss?", values = c("blue","red"))+
  xlab("median cycle length before first positive preg. test")+
  theme(legend.position = "top")

g

ggsave(filename = paste0(IO$panels, "median_cycle_length_before_first_preg.pdf"), g, width = 5, height = 5)



g = ggplot(u, aes(x = sd_cycle_length_4, fill = is_first_preg_a_PL))+
  geom_histogram(aes(y = ..density..), col = NA, alpha = 0.3, position = "identity", binwidth = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_j, limits = c(0,42))+
  scale_fill_manual(name = "Does 1st pregnancy end up in a preg. loss?", values = c("blue","red"))+
  xlab("standard deviation in cycle length before 1st pos. preg. test")+
  theme(legend.position = "top")
g

ggsave(filename = paste0(IO$panels, "sd_cycle_length_before_first_preg.pdf"), g, width = 5, height = 5)



g = ggplot(u, aes(x = log10(sd_cycle_length_4), fill = is_first_preg_a_PL))+
  geom_histogram(aes(y = ..density..), col = NA, alpha = 0.3, position = "identity", binwidth = 0.1)+
  #scale_x_continuous(breaks = log10(viz$xaxis_j))+ # , limits = c(0,42)
  scale_fill_manual(name = "Does 1st pregnancy end up in a preg. loss?", values = c("blue","red"))+
  xlab("standard deviation (log10) in cycle length before 1st pos. preg. test")+
  theme(legend.position = "top")
g

ggsave(filename = paste0(IO$panels, "log10_sd_cycle_length_before_first_preg.pdf"), g, width = 5, height = 5)



qqplot(x=  u$median_cycle_length_4[which(u$is_first_preg_a_PL == "Yes")], 
       y = u$median_cycle_length_4[which(u$is_first_preg_a_PL == "No")], 
       pch = 16, cex = 0.5, col = rgb(0,0,0,0.3),
       xlim = c(0,50), ylim = c(0,50))
abline(a = 0, b = 1)



qqplot(x=  u$sd_cycle_length_4[which(u$is_first_preg_a_PL == "Yes")], 
       y = u$sd_cycle_length_4[which(u$is_first_preg_a_PL == "No")], 
       pch = 16, cex = 0.5, col = rgb(0,0,0,0.3),
       xlim = c(0,42), ylim = c(0,42),
       main = "cycle length variability",
       xlab = "1st preg. ends up in a PL", ylab = "1st preg. ends up in a LB")
abline(a = 0, b = 1)





g = ggplot(u, aes(x = first_cycle_preg-1, fill = is_first_preg_a_PL))+
  geom_histogram(aes(y = ..density..), col = NA, alpha = 0.3, position = "identity", binwidth = 1)+
  scale_fill_manual(name = "Does 1st pregnancy end up in a preg. loss?", values = c("blue","red"))+
  xlab("# of cycles before getting pregnant")+
  theme(legend.position = "top")
g

ggsave(filename = paste0(IO$panels, "number_of_cycles_before_first_preg.pdf"), g, width = 5, height = 5)



qqplot(x=  u$first_cycle_preg[which(u$is_first_preg_a_PL == "Yes")], 
       y = u$first_cycle_preg[which(u$is_first_preg_a_PL == "No")], 
       pch = 16, cex = 0.5, col = rgb(0,0,0,0.3),
       xlim = c(0,80), ylim = c(0,80),
       main = "# of cycles before getting pregnant",
       xlab = "1st preg. ends up in a PL", ylab = "1st preg. ends up in a LB")
abline(a = 0, b = 1)





g = ggplot(u, aes(x = time_to_first_pos_test, fill = is_first_preg_a_PL))+
  geom_histogram(aes(y = ..density..), col = NA, alpha = 0.3, position = "identity", binwidth = 1/12)+
  scale_fill_manual(name = "Does 1st pregnancy end up in a preg. loss?", values = c("blue","red"))+
  xlab("# of years before 1st positive preg. test")+
  theme(legend.position = "top")
g

ggsave(filename = paste0(IO$panels, "time_before_first_preg.pdf"), g, width = 5, height = 5)


qqplot(x=  u$time_to_first_pos_test[which(u$is_first_preg_a_PL == "Yes")], 
       y = u$time_to_first_pos_test[which(u$is_first_preg_a_PL == "No")], 
       pch = 16, cex = 0.5, col = rgb(0,0,0,0.3),
       xlim = c(0,5), ylim = c(0,5),
       main = "time before getting pregnant",
       xlab = "1st preg. ends up in a PL", ylab = "1st preg. ends up in a LB")
abline(a = 0, b = 1)

```




```{r figures cycle lengths predictor - old}

load(file = paste0(IO$output_data,"users.Rdata"), verbose = TRUE)

users$any_PL = ifelse(users$n_PL>0, "Yes", ifelse(users$n_LB>0,"No",NA))

u = users[which(!is.na(users$any_PL)),]


g = ggplot(u, aes(x = cycle_length_before_preg_median, fill = any_PL))+
  geom_histogram(aes(y = ..density..), col = NA, alpha = 0.5, position = "identity", binwidth = 1)+
  scale_x_continuous(breaks = viz$xaxis_j, limits = c(14,70))+
  scale_fill_manual(name = "experienced any preg. loss", values = c("blue","red"))+
  xlab("median cycle length before first positive preg. test")+
  theme(legend.position = "top")

g


ggsave(filename = paste0(IO$panels, "median_cycle_length_before_first_preg.pdf"), g, width = 5, height = 5)




g = ggplot(u, aes(x = cycle_length_before_preg_sd, fill = any_PL))+
  geom_histogram(aes(y = ..density..), col = NA, alpha = 0.5, position = "identity", binwidth = 0.5)+
  scale_x_continuous(breaks = viz$xaxis_j, limits = c(0,42))+
  scale_fill_manual(name = "experienced any preg. loss", values = c("blue","red"))+
  xlab("standard deviation in cycle length before 1st pos. preg. test")+
  theme(legend.position = "top")
g

ggsave(filename = paste0(IO$panels, "sd_cycle_length_before_first_preg.pdf"), g, width = 5, height = 5)




qqplot(x=  u$cycle_length_before_preg_sd[which(u$any_PL == "Yes")], 
       y = u$cycle_length_before_preg_sd[which(u$any_PL == "No")], 
       pch = 16, cex = 0.5, col = rgb(0,0,0,0.3),
       xlim = c(0,50), ylim = c(0,50))
abline(a = 0, b = 1)



qqplot(x=  u$cycle_length_before_preg_median[which(u$any_PL == "Yes")], 
       y = u$cycle_length_before_preg_median[which(u$any_PL == "No")], 
       pch = 16, cex = 0.5, col = rgb(0,0,0,0.3),
       xlim = c(0,91), ylim = c(0,91))
abline(a = 0, b = 1)


```

